--Neck
insert into muscle (weightId, name, body_part) VALUES
  (1, 'platysma', 'neck'),
  (2, 'sternocleidomastoid', 'neck'),
  (3, 'digastric', 'neck'),
  (4, 'stylohyoid', 'neck'),
  (5, 'mylohyoid', 'neck'),
  (6, 'geniohyoid', 'neck'),
  (7, 'sternohyoid', 'neck'),
  (8, 'sternothyroid', 'neck'),
  (9, 'thyrohyoid', 'neck'),
  (10, 'omohyoid', 'neck'),
  (11, 'scalene muscles', 'neck'),
  (12, 'anterior', 'neck'),
  (13, 'medius', 'neck'),
  (14, 'posterior', 'neck'),
  (15, 'levator scapulae', 'neck'),
  (16, 'rectus capitis lateralis', 'neck'),
  (17, 'obliquus capitis superior', 'neck'),
  (18, 'rectus capitis posterior minor', 'neck'),
  (19, 'rectus capitis posterior major', 'neck'),
  (20, 'semispinalis capitis', 'neck'),
  (21, 'longissimus capitis', 'neck'),
  (22, 'splenius capitis', 'neck')