version: '2'
services:
    thefitnation-elasticsearch:
        container_name: thefitnation-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/TheFitNation/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
