version: '2'
services:
    thefitnation-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/TheFitNation/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=TheFitNation
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
